// <auto-generated />
using System;
using CountriesCapitalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CountriesCapitalAPI.Migrations
{
    [DbContext(typeof(CountryContext))]
    [Migration("20221222013742_CreateInitial")]
    partial class CreateInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CountriesCapitalAPI.Models.CountryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("countryItems");
                });

            modelBuilder.Entity("CountriesCapitalAPI.Models.PopulationCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryItemId")
                        .HasColumnType("int");

                    b.Property<string>("Reliabilty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryItemId");

                    b.ToTable("PopulationCounts");
                });

            modelBuilder.Entity("CountriesCapitalAPI.Models.PopulationCount", b =>
                {
                    b.HasOne("CountriesCapitalAPI.Models.CountryItem", null)
                        .WithMany("PopulationCounts")
                        .HasForeignKey("CountryItemId");
                });

            modelBuilder.Entity("CountriesCapitalAPI.Models.CountryItem", b =>
                {
                    b.Navigation("PopulationCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
